### ISSUE TITLE
Plots not updating after latest work on Cells lifecycle

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#184]
If you go to the object_database_webtest and look at the Graph services and go to the 'timestamp' one, you should see the graph add a point each time you click the button. That pathway appears to be inactive now.

As part of fixing this, lets get a couple of plot examples in the playground, where we specifically test data update and navigation.

**Comment by darth-cheney** [comment]
I have pushed a quickfix to [`eric-plot-fix`](https://github.com/APrioriInvestments/nativepython/tree/eric-plot-fix) that should resolve this problem.
  
For my own reference (and posterity) let me explain the problem here. Plot uses a sub-cell type called `_PlotUpdater` and what we had done on the component side is to ensure that whenever that kind of Cell updates it finds its matching "real Plot" in the DOM and passes data to its component.
  
Unfortunately we were doing this in the `componentDidLoad` lifecycle method, which will only fire the first time a component/cell instance is added. Before the lifecycle refactor, this was actually happening all the time: we were not keeping reference to components but simply rendering them and then tossing away the objects, creating a new instance when new render commands came through. This means `componentDidLoad` was, back then, being called whenever a Cell updates its corresponding Component.
  
This is -- correctly -- no longer how it works. Unfortunately that means we have the issue in question.
  
The solution was to add a new and useful lifecycle method to all Components called `componentDidUpdate`. This will be called anytime the `#cellUpdated` message is sent for a particular Cell whose Component is *already loaded in the UI*. It will be called every time after the first time it is created.
  
In the referenced hotfix branch, I have updated `_PlotUpdater` accordingly.
  
I recommend a complete refactor of `Plot` as a part of the future work dealing with messages and events sent to specific Cell components. We probably don't even need `_PlotUpdater`, but rather the kind of message handling extensions we proposed a while back, along with extensions for `Plot` that allow us to send its components straightforward (though cell specific) messages.
