### ISSUE TITLE
Small change in code formatting causes compilation to break

### ISSUE THREAD

**Issue by atzannes** [APrioriInvestments/typed_python#250]
See commit https://github.com/APrioriInvestments/typed_python/commit/b6a6cd7022d98d47dc4055f825c49c891925a355

which is on branch https://github.com/APrioriInvestments/typed_python/tree/bug-formatting-breaks-test

**Comment by atzannes** [comment]
I discovered this by running black code formatter on the code and discovering that it broke this test.

**Comment by braxtonmckee** [comment]
I've seen this before. When we're looking to serialize or compile a lambda
function, we do some nasty text manipulation and then evaluate the
expression to pull out the body of the lambda function. This works great
for 'def' methods because they always span a contiguous block of lines, but
for lambdas it can break when there are other expressions on the same set
of lines. This turns out to be quite brittle, and we should fix it.
Probably we should be parsing the entire file and then finding the AST node
for the lambda and working with that instead.
