### ISSUE TITLE
ListOf.resize() is not reading __init__

### ISSUE THREAD

**Issue by aaronmlevy** [APrioriInvestments/typed_python#361]
Please see `test_resize_init` in `/typed_python/types_test.py`.

**Comment by braxtonmckee** [comment]
This is actually the currently desired behavior.

We don't allow __init__ to define a default constructor, nor do we allow default construction of the elements of a class that themselves have classes, because otherwise it's possible to get a default constructor that runs forever. We want our constructor/destructor semantics to never throw exceptions or fail, because unlike C++ we don't have formal destructors or a model for handling exceptions during object teardown.

If you want to initialize a list of like this, I'd recommend making a little function to construct a list from a factory:

```
def listOfFrom(T, ct, f):
    res = ListOf(T)()
    for i in range(ct):
        res.append(f())
    return res

listOfFrom(C, 100, lambda: C())
```
