### ISSUE TITLE
can't return types of Functions from a TypeFunction

### ISSUE THREAD

**Issue by affine-root-system** [APrioriInvestments/typed_python#380]
This pattern used to work (I was using it):
```
@TypeFunction
def f(T):
  @type
  @Function
  def g():
    return T()
  return g

assert f(int)()() == 0
```
Now, it gives a
```
NameError: free variable 'T' referenced before assignment in enclosing scope
```
If you replace the @Function with an @Entrypoint, you segfault (naturally).

**Comment by braxtonmckee** [comment]
Segfault is fixed in commits referenced above. But the preferred way of doing this right now is to do

```
@TypeFunction
def f(T):
    class g:
        def __call__(self):
            return T()
    return g
```

which makes it clear that you're embedding a reference to T in a _type_ rather than as part of the closure of a function.  Classes always bind the free variables of their methods as part of the type object, since the class object itself is a Type* in the underlying C and is therefore a singleton.
